<h3>Import useful librairies and load csv file created previously</h3>

In [1]:
import pandas as pd
import numpy as np

In [2]:
dt = pd.read_csv("dirtytweets.csv")
dt

,username,tweet,date,name,creation,followers,following
0,admzawa,@SherazadeSmh Y a Bcp de folle on le sait tqt ...,Mon Oct 20 18:50:00 +0000 2025,Adam🇵🇸,Tue May 17 19:16:46 +0000 2022,14,129
1,zipetteenfolie,Le mec qui a inventé la depression viens discu...,Mon Oct 20 18:49:21 +0000 2025,3pm.mvt,Tue Jan 01 14:37:58 +0000 2019,284,1053
2,Tej4s27,Post Travis concert depression,Mon Oct 20 18:48:00 +0000 2025,kami,Sat Jan 20 08:02:37 +0000 2024,726,397
3,ssclim77,Ce qu'une dépression peut faire à ta santé aus...,Mon Oct 20 18:47:45 +0000 2025,Moh 🇲🇦,Mon Dec 16 10:46:56 +0000 2024,838,458
4,koruxy1,@nominomm si elle était en depression ca expli...,Mon Oct 20 18:40:21 +0000 2025,koruxy,Mon Sep 19 06:38:06 +0000 2022,40,146
...,...,...,...,...,...,...,...
175,Peguy_Certifie,@ActuFoot_ 😂😂😂😂😂😂😂😂😂😂😂😂😂\n\nLA DEPRESSION VA T...,Mon Oct 20 13:34:51 +0000 2025,💀 𝐌𝐑. 𝐓 𝐎 𝐍 𝐓 𝐈 𝐍 𝐄 🩸,Fri Oct 20 19:07:56 +0000 2017,42717,470
176,iwisxh,Vous voyez ça ? Ça m’écœure. Je me bâts depuis...,Mon Oct 20 13:34:48 +0000 2025,❯❯❯❯,Wed Aug 28 11:40:51 +0000 2019,158,175
177,MonaRodriguezzz,Post vacation depression,Mon Oct 20 13:34:47 +0000 2025,Ms Rodriguez,Sat Aug 24 23:25:43 +0000 2019,367,305
178,kindormad,@Baby_Princess_L Est ce que j’ai dit ça même? ...,Mon Oct 20 13:34:33 +0000 2025,Abe 🍉,Thu May 08 20:41:43 +0000 2014,671,560
179,laTrompette_fr,Donner des médicaments aux personnes souffrant...,Mon Oct 20 13:34:24 +0000 2025,laTrompette.fr,Mon Aug 15 08:31:08 +0000 2016,492,162

In [3]:
text = dt.groupby(["tweet"]).describe()
text

                                                   followers                \
                                                       count      mean std
tweet
#JournéeMondialeDuDiabète\nCette année, la @Fed...       1.0    5200.0 NaN
(Vous avez jms vécu de dépression)                       1.0     259.0 NaN
1- MON BB MA PREF SERVICE 5⭐️💋\n2- en vrai cv s...       1.0    3091.0 NaN
40 personnes pr choisir une chanson et une affi...       1.0    3406.0 NaN
@ActuFoot_ 😂😂😂😂😂😂😂😂😂😂😂😂😂\n\nLA DEPRESSION VA TU...       1.0   42717.0 NaN
...                                                      ...       ...  ..
🌧️ La #pluie et le vent touchent la France cett...       1.0  179214.0 NaN
🌧️Le dimanche 19 octobre, une dépression a appo...       1.0     813.0 NaN
🎙️Le pédopsychiatre Marcel Rufo s’inquiète de l...       1.0   50610.0 NaN
🎧 Nouvel épisode de notre podcast Afrique 360°....       1.0  233250.0 NaN
🤣🤣🤣🤣 ya pas sherpa pour te porter hein ptit nul...       1.0     184.0 NaN

                                                                        \
                                                         min       25%
tweet
#JournéeMondialeDuDiabète\nCette année, la @Fed...    5200.0    5200.0
(Vous avez jms vécu de dépression)                     259.0     259.0
1- MON BB MA PREF SERVICE 5⭐️💋\n2- en vrai cv s...    3091.0    3091.0
40 personnes pr choisir une chanson et une affi...    3406.0    3406.0
@ActuFoot_ 😂😂😂😂😂😂😂😂😂😂😂😂😂\n\nLA DEPRESSION VA TU...   42717.0   42717.0
...                                                      ...       ...
🌧️ La #pluie et le vent touchent la France cett...  179214.0  179214.0
🌧️Le dimanche 19 octobre, une dépression a appo...     813.0     813.0
🎙️Le pédopsychiatre Marcel Rufo s’inquiète de l...   50610.0   50610.0
🎧 Nouvel épisode de notre podcast Afrique 360°....  233250.0  233250.0
🤣🤣🤣🤣 ya pas sherpa pour te porter hein ptit nul...     184.0     184.0

                                                                        \
                                                         50%       75%
tweet
#JournéeMondialeDuDiabète\nCette année, la @Fed...    5200.0    5200.0
(Vous avez jms vécu de dépression)                     259.0     259.0
1- MON BB MA PREF SERVICE 5⭐️💋\n2- en vrai cv s...    3091.0    3091.0
40 personnes pr choisir une chanson et une affi...    3406.0    3406.0
@ActuFoot_ 😂😂😂😂😂😂😂😂😂😂😂😂😂\n\nLA DEPRESSION VA TU...   42717.0   42717.0
...                                                      ...       ...
🌧️ La #pluie et le vent touchent la France cett...  179214.0  179214.0
🌧️Le dimanche 19 octobre, une dépression a appo...     813.0     813.0
🎙️Le pédopsychiatre Marcel Rufo s’inquiète de l...   50610.0   50610.0
🎧 Nouvel épisode de notre podcast Afrique 360°....  233250.0  233250.0
🤣🤣🤣🤣 ya pas sherpa pour te porter hein ptit nul...     184.0     184.0

                                                             following  \
                                                         max     count
tweet
#JournéeMondialeDuDiabète\nCette année, la @Fed...    5200.0       1.0
(Vous avez jms vécu de dépression)                     259.0       1.0
1- MON BB MA PREF SERVICE 5⭐️💋\n2- en vrai cv s...    3091.0       1.0
40 personnes pr choisir une chanson et une affi...    3406.0       1.0
@ActuFoot_ 😂😂😂😂😂😂😂😂😂😂😂😂😂\n\nLA DEPRESSION VA TU...   42717.0       1.0
...                                                      ...       ...
🌧️ La #pluie et le vent touchent la France cett...  179214.0       1.0
🌧️Le dimanche 19 octobre, une dépression a appo...     813.0       1.0
🎙️Le pédopsychiatre Marcel Rufo s’inquiète de l...   50610.0       1.0
🎧 Nouvel épisode de notre podcast Afrique 360°....  233250.0       1.0
🤣🤣🤣🤣 ya pas sherpa pour te porter hein ptit nul...     184.0       1.0

                                                                        \
                                                      mean std     min
tweet
#JournéeMondialeDuDiabète\nCette année, la @Fed...  1277.0 NaN  1277.0
(Vous avez jms vécu de dépression)                    72.0 NaN    72.0
1- MON BB MA PREF SERVICE 5⭐️💋\n2- en vrai cv s...   820.0 NaN   820.0
40 personnes pr choisir une chanson et une affi...  1213.0 NaN  1213.0
@ActuFoot_ 😂😂😂😂😂😂😂😂😂😂😂😂😂\n\nLA DEPRESSION VA TU...   470.0 NaN   470.0
...                                                    ...  ..     ...
🌧️ La #pluie et le vent touchent la France cett...  1074.0 NaN  1074.0
🌧️Le dimanche 19 octobre, une dépression a appo...    40.0 NaN    40.0
🎙️Le pédopsychiatre Marcel Rufo s’inquiète de l...   475.0 NaN   475.0
🎧 Nouvel épisode de notre podcast Afrique 360°....  2667.0 NaN  2667.0
🤣🤣🤣🤣 ya pas sherpa pour te porter hein ptit nul...   297.0 NaN   297.0

                                                                            \
                                                       25%     50%     75%
tweet
#JournéeMondialeDuDiabète\nCette année, la @Fed...  1277.0  1277.0  1277.0
(Vous avez jms vécu de dépression)                    72.0    72.0    72.0
1- MON BB MA PREF SERVICE 5⭐️💋\n2- en vrai cv s...   820.0   820.0   820.0
40 personnes pr choisir une chanson et une affi...  1213.0  1213.0  1213.0
@ActuFoot_ 😂😂😂😂😂😂😂😂😂😂😂😂😂\n\nLA DEPRESSION VA TU...   470.0   470.0   470.0
...                                                    ...     ...     ...
🌧️ La #pluie et le vent touchent la France cett...  1074.0  1074.0  1074.0
🌧️Le dimanche 19 octobre, une dépression a appo...    40.0    40.0    40.0
🎙️Le pédopsychiatre Marcel Rufo s’inquiète de l...   475.0   475.0   475.0
🎧 Nouvel épisode de notre podcast Afrique 360°....  2667.0  2667.0  2667.0
🤣🤣🤣🤣 ya pas sherpa pour te porter hein ptit nul...   297.0   297.0   297.0


                                                       max
tweet
#JournéeMondialeDuDiabète\nCette année, la @Fed...  1277.0
(Vous avez jms vécu de dépression)                    72.0
1- MON BB MA PREF SERVICE 5⭐️💋\n2- en vrai cv s...   820.0
40 personnes pr choisir une chanson et une affi...  1213.0
@ActuFoot_ 😂😂😂😂😂😂😂😂😂😂😂😂😂\n\nLA DEPRESSION VA TU...   470.0
...                                                    ...
🌧️ La #pluie et le vent touchent la France cett...  1074.0
🌧️Le dimanche 19 octobre, une dépression a appo...    40.0
🎙️Le pédopsychiatre Marcel Rufo s’inquiète de l...   475.0
🎧 Nouvel épisode de notre podcast Afrique 360°....  2667.0
🤣🤣🤣🤣 ya pas sherpa pour te porter hein ptit nul...   297.0

[180 rows x 16 columns]

In [4]:
dt["tweet"] = dt['tweet'].str.replace("\n", "")

In [5]:
dt

,username,tweet,date,name,creation,followers,following
0,admzawa,@SherazadeSmh Y a Bcp de folle on le sait tqt ...,Mon Oct 20 18:50:00 +0000 2025,Adam🇵🇸,Tue May 17 19:16:46 +0000 2022,14,129
1,zipetteenfolie,Le mec qui a inventé la depression viens discu...,Mon Oct 20 18:49:21 +0000 2025,3pm.mvt,Tue Jan 01 14:37:58 +0000 2019,284,1053
2,Tej4s27,Post Travis concert depression,Mon Oct 20 18:48:00 +0000 2025,kami,Sat Jan 20 08:02:37 +0000 2024,726,397
3,ssclim77,Ce qu'une dépression peut faire à ta santé aus...,Mon Oct 20 18:47:45 +0000 2025,Moh 🇲🇦,Mon Dec 16 10:46:56 +0000 2024,838,458
4,koruxy1,@nominomm si elle était en depression ca expli...,Mon Oct 20 18:40:21 +0000 2025,koruxy,Mon Sep 19 06:38:06 +0000 2022,40,146
...,...,...,...,...,...,...,...
175,Peguy_Certifie,@ActuFoot_ 😂😂😂😂😂😂😂😂😂😂😂😂😂LA DEPRESSION VA TUER ...,Mon Oct 20 13:34:51 +0000 2025,💀 𝐌𝐑. 𝐓 𝐎 𝐍 𝐓 𝐈 𝐍 𝐄 🩸,Fri Oct 20 19:07:56 +0000 2017,42717,470
176,iwisxh,Vous voyez ça ? Ça m’écœure. Je me bâts depuis...,Mon Oct 20 13:34:48 +0000 2025,❯❯❯❯,Wed Aug 28 11:40:51 +0000 2019,158,175
177,MonaRodriguezzz,Post vacation depression,Mon Oct 20 13:34:47 +0000 2025,Ms Rodriguez,Sat Aug 24 23:25:43 +0000 2019,367,305
178,kindormad,@Baby_Princess_L Est ce que j’ai dit ça même? ...,Mon Oct 20 13:34:33 +0000 2025,Abe 🍉,Thu May 08 20:41:43 +0000 2014,671,560
179,laTrompette_fr,Donner des médicaments aux personnes souffrant...,Mon Oct 20 13:34:24 +0000 2025,laTrompette.fr,Mon Aug 15 08:31:08 +0000 2016,492,162

In [6]:
dt.insert(3, "hour", 0)
dt.insert(4,"year", 0)
dt.insert(7, "year_of_creation", 0)

In [7]:
dt

,username,tweet,date,hour,year,name,creation,year_of_creation,followers,following
0,admzawa,@SherazadeSmh Y a Bcp de folle on le sait tqt ...,Mon Oct 20 18:50:00 +0000 2025,0,0,Adam🇵🇸,Tue May 17 19:16:46 +0000 2022,0,14,129
1,zipetteenfolie,Le mec qui a inventé la depression viens discu...,Mon Oct 20 18:49:21 +0000 2025,0,0,3pm.mvt,Tue Jan 01 14:37:58 +0000 2019,0,284,1053
2,Tej4s27,Post Travis concert depression,Mon Oct 20 18:48:00 +0000 2025,0,0,kami,Sat Jan 20 08:02:37 +0000 2024,0,726,397
3,ssclim77,Ce qu'une dépression peut faire à ta santé aus...,Mon Oct 20 18:47:45 +0000 2025,0,0,Moh 🇲🇦,Mon Dec 16 10:46:56 +0000 2024,0,838,458
4,koruxy1,@nominomm si elle était en depression ca expli...,Mon Oct 20 18:40:21 +0000 2025,0,0,koruxy,Mon Sep 19 06:38:06 +0000 2022,0,40,146
...,...,...,...,...,...,...,...,...,...,...
175,Peguy_Certifie,@ActuFoot_ 😂😂😂😂😂😂😂😂😂😂😂😂😂LA DEPRESSION VA TUER ...,Mon Oct 20 13:34:51 +0000 2025,0,0,💀 𝐌𝐑. 𝐓 𝐎 𝐍 𝐓 𝐈 𝐍 𝐄 🩸,Fri Oct 20 19:07:56 +0000 2017,0,42717,470
176,iwisxh,Vous voyez ça ? Ça m’écœure. Je me bâts depuis...,Mon Oct 20 13:34:48 +0000 2025,0,0,❯❯❯❯,Wed Aug 28 11:40:51 +0000 2019,0,158,175
177,MonaRodriguezzz,Post vacation depression,Mon Oct 20 13:34:47 +0000 2025,0,0,Ms Rodriguez,Sat Aug 24 23:25:43 +0000 2019,0,367,305
178,kindormad,@Baby_Princess_L Est ce que j’ai dit ça même? ...,Mon Oct 20 13:34:33 +0000 2025,0,0,Abe 🍉,Thu May 08 20:41:43 +0000 2014,0,671,560
179,laTrompette_fr,Donner des médicaments aux personnes souffrant...,Mon Oct 20 13:34:24 +0000 2025,0,0,laTrompette.fr,Mon Aug 15 08:31:08 +0000 2016,0,492,162

In [8]:
#All the dates are written the same way : 'Day Month Day(digit)' & at the end the year
# So the format is the same : 3 letters for the day + " " + 3 letters for the month + " " + 2 digits for the day
# We want to export the year for the date to the year column created previously

In [9]:
dt["hour"] = dt['date'].str[11:16]
dt

,username,tweet,date,hour,year,name,creation,year_of_creation,followers,following
0,admzawa,@SherazadeSmh Y a Bcp de folle on le sait tqt ...,Mon Oct 20 18:50:00 +0000 2025,18:50,0,Adam🇵🇸,Tue May 17 19:16:46 +0000 2022,0,14,129
1,zipetteenfolie,Le mec qui a inventé la depression viens discu...,Mon Oct 20 18:49:21 +0000 2025,18:49,0,3pm.mvt,Tue Jan 01 14:37:58 +0000 2019,0,284,1053
2,Tej4s27,Post Travis concert depression,Mon Oct 20 18:48:00 +0000 2025,18:48,0,kami,Sat Jan 20 08:02:37 +0000 2024,0,726,397
3,ssclim77,Ce qu'une dépression peut faire à ta santé aus...,Mon Oct 20 18:47:45 +0000 2025,18:47,0,Moh 🇲🇦,Mon Dec 16 10:46:56 +0000 2024,0,838,458
4,koruxy1,@nominomm si elle était en depression ca expli...,Mon Oct 20 18:40:21 +0000 2025,18:40,0,koruxy,Mon Sep 19 06:38:06 +0000 2022,0,40,146
...,...,...,...,...,...,...,...,...,...,...
175,Peguy_Certifie,@ActuFoot_ 😂😂😂😂😂😂😂😂😂😂😂😂😂LA DEPRESSION VA TUER ...,Mon Oct 20 13:34:51 +0000 2025,13:34,0,💀 𝐌𝐑. 𝐓 𝐎 𝐍 𝐓 𝐈 𝐍 𝐄 🩸,Fri Oct 20 19:07:56 +0000 2017,0,42717,470
176,iwisxh,Vous voyez ça ? Ça m’écœure. Je me bâts depuis...,Mon Oct 20 13:34:48 +0000 2025,13:34,0,❯❯❯❯,Wed Aug 28 11:40:51 +0000 2019,0,158,175
177,MonaRodriguezzz,Post vacation depression,Mon Oct 20 13:34:47 +0000 2025,13:34,0,Ms Rodriguez,Sat Aug 24 23:25:43 +0000 2019,0,367,305
178,kindormad,@Baby_Princess_L Est ce que j’ai dit ça même? ...,Mon Oct 20 13:34:33 +0000 2025,13:34,0,Abe 🍉,Thu May 08 20:41:43 +0000 2014,0,671,560
179,laTrompette_fr,Donner des médicaments aux personnes souffrant...,Mon Oct 20 13:34:24 +0000 2025,13:34,0,laTrompette.fr,Mon Aug 15 08:31:08 +0000 2016,0,492,162

In [10]:
dt["year"] = dt["date"].str.slice(-4)

In [11]:
dt

,username,tweet,date,hour,year,name,creation,year_of_creation,followers,following
0,admzawa,@SherazadeSmh Y a Bcp de folle on le sait tqt ...,Mon Oct 20 18:50:00 +0000 2025,18:50,2025,Adam🇵🇸,Tue May 17 19:16:46 +0000 2022,0,14,129
1,zipetteenfolie,Le mec qui a inventé la depression viens discu...,Mon Oct 20 18:49:21 +0000 2025,18:49,2025,3pm.mvt,Tue Jan 01 14:37:58 +0000 2019,0,284,1053
2,Tej4s27,Post Travis concert depression,Mon Oct 20 18:48:00 +0000 2025,18:48,2025,kami,Sat Jan 20 08:02:37 +0000 2024,0,726,397
3,ssclim77,Ce qu'une dépression peut faire à ta santé aus...,Mon Oct 20 18:47:45 +0000 2025,18:47,2025,Moh 🇲🇦,Mon Dec 16 10:46:56 +0000 2024,0,838,458
4,koruxy1,@nominomm si elle était en depression ca expli...,Mon Oct 20 18:40:21 +0000 2025,18:40,2025,koruxy,Mon Sep 19 06:38:06 +0000 2022,0,40,146
...,...,...,...,...,...,...,...,...,...,...
175,Peguy_Certifie,@ActuFoot_ 😂😂😂😂😂😂😂😂😂😂😂😂😂LA DEPRESSION VA TUER ...,Mon Oct 20 13:34:51 +0000 2025,13:34,2025,💀 𝐌𝐑. 𝐓 𝐎 𝐍 𝐓 𝐈 𝐍 𝐄 🩸,Fri Oct 20 19:07:56 +0000 2017,0,42717,470
176,iwisxh,Vous voyez ça ? Ça m’écœure. Je me bâts depuis...,Mon Oct 20 13:34:48 +0000 2025,13:34,2025,❯❯❯❯,Wed Aug 28 11:40:51 +0000 2019,0,158,175
177,MonaRodriguezzz,Post vacation depression,Mon Oct 20 13:34:47 +0000 2025,13:34,2025,Ms Rodriguez,Sat Aug 24 23:25:43 +0000 2019,0,367,305
178,kindormad,@Baby_Princess_L Est ce que j’ai dit ça même? ...,Mon Oct 20 13:34:33 +0000 2025,13:34,2025,Abe 🍉,Thu May 08 20:41:43 +0000 2014,0,671,560
179,laTrompette_fr,Donner des médicaments aux personnes souffrant...,Mon Oct 20 13:34:24 +0000 2025,13:34,2025,laTrompette.fr,Mon Aug 15 08:31:08 +0000 2016,0,492,162

In [12]:
dt.insert(3,"day", 0)

In [13]:
dt.day = dt.date.str[8:10]
dt

,username,tweet,date,day,hour,year,name,creation,year_of_creation,followers,following
0,admzawa,@SherazadeSmh Y a Bcp de folle on le sait tqt ...,Mon Oct 20 18:50:00 +0000 2025,20,18:50,2025,Adam🇵🇸,Tue May 17 19:16:46 +0000 2022,0,14,129
1,zipetteenfolie,Le mec qui a inventé la depression viens discu...,Mon Oct 20 18:49:21 +0000 2025,20,18:49,2025,3pm.mvt,Tue Jan 01 14:37:58 +0000 2019,0,284,1053
2,Tej4s27,Post Travis concert depression,Mon Oct 20 18:48:00 +0000 2025,20,18:48,2025,kami,Sat Jan 20 08:02:37 +0000 2024,0,726,397
3,ssclim77,Ce qu'une dépression peut faire à ta santé aus...,Mon Oct 20 18:47:45 +0000 2025,20,18:47,2025,Moh 🇲🇦,Mon Dec 16 10:46:56 +0000 2024,0,838,458
4,koruxy1,@nominomm si elle était en depression ca expli...,Mon Oct 20 18:40:21 +0000 2025,20,18:40,2025,koruxy,Mon Sep 19 06:38:06 +0000 2022,0,40,146
...,...,...,...,...,...,...,...,...,...,...,...
175,Peguy_Certifie,@ActuFoot_ 😂😂😂😂😂😂😂😂😂😂😂😂😂LA DEPRESSION VA TUER ...,Mon Oct 20 13:34:51 +0000 2025,20,13:34,2025,💀 𝐌𝐑. 𝐓 𝐎 𝐍 𝐓 𝐈 𝐍 𝐄 🩸,Fri Oct 20 19:07:56 +0000 2017,0,42717,470
176,iwisxh,Vous voyez ça ? Ça m’écœure. Je me bâts depuis...,Mon Oct 20 13:34:48 +0000 2025,20,13:34,2025,❯❯❯❯,Wed Aug 28 11:40:51 +0000 2019,0,158,175
177,MonaRodriguezzz,Post vacation depression,Mon Oct 20 13:34:47 +0000 2025,20,13:34,2025,Ms Rodriguez,Sat Aug 24 23:25:43 +0000 2019,0,367,305
178,kindormad,@Baby_Princess_L Est ce que j’ai dit ça même? ...,Mon Oct 20 13:34:33 +0000 2025,20,13:34,2025,Abe 🍉,Thu May 08 20:41:43 +0000 2014,0,671,560
179,laTrompette_fr,Donner des médicaments aux personnes souffrant...,Mon Oct 20 13:34:24 +0000 2025,20,13:34,2025,laTrompette.fr,Mon Aug 15 08:31:08 +0000 2016,0,492,162

In [14]:
dt.insert(4,"month",0)

In [15]:
dt.month = dt.date.str[4:7]
dt

,username,tweet,date,day,month,hour,year,name,creation,year_of_creation,followers,following
0,admzawa,@SherazadeSmh Y a Bcp de folle on le sait tqt ...,Mon Oct 20 18:50:00 +0000 2025,20,Oct,18:50,2025,Adam🇵🇸,Tue May 17 19:16:46 +0000 2022,0,14,129
1,zipetteenfolie,Le mec qui a inventé la depression viens discu...,Mon Oct 20 18:49:21 +0000 2025,20,Oct,18:49,2025,3pm.mvt,Tue Jan 01 14:37:58 +0000 2019,0,284,1053
2,Tej4s27,Post Travis concert depression,Mon Oct 20 18:48:00 +0000 2025,20,Oct,18:48,2025,kami,Sat Jan 20 08:02:37 +0000 2024,0,726,397
3,ssclim77,Ce qu'une dépression peut faire à ta santé aus...,Mon Oct 20 18:47:45 +0000 2025,20,Oct,18:47,2025,Moh 🇲🇦,Mon Dec 16 10:46:56 +0000 2024,0,838,458
4,koruxy1,@nominomm si elle était en depression ca expli...,Mon Oct 20 18:40:21 +0000 2025,20,Oct,18:40,2025,koruxy,Mon Sep 19 06:38:06 +0000 2022,0,40,146
...,...,...,...,...,...,...,...,...,...,...,...,...
175,Peguy_Certifie,@ActuFoot_ 😂😂😂😂😂😂😂😂😂😂😂😂😂LA DEPRESSION VA TUER ...,Mon Oct 20 13:34:51 +0000 2025,20,Oct,13:34,2025,💀 𝐌𝐑. 𝐓 𝐎 𝐍 𝐓 𝐈 𝐍 𝐄 🩸,Fri Oct 20 19:07:56 +0000 2017,0,42717,470
176,iwisxh,Vous voyez ça ? Ça m’écœure. Je me bâts depuis...,Mon Oct 20 13:34:48 +0000 2025,20,Oct,13:34,2025,❯❯❯❯,Wed Aug 28 11:40:51 +0000 2019,0,158,175
177,MonaRodriguezzz,Post vacation depression,Mon Oct 20 13:34:47 +0000 2025,20,Oct,13:34,2025,Ms Rodriguez,Sat Aug 24 23:25:43 +0000 2019,0,367,305
178,kindormad,@Baby_Princess_L Est ce que j’ai dit ça même? ...,Mon Oct 20 13:34:33 +0000 2025,20,Oct,13:34,2025,Abe 🍉,Thu May 08 20:41:43 +0000 2014,0,671,560
179,laTrompette_fr,Donner des médicaments aux personnes souffrant...,Mon Oct 20 13:34:24 +0000 2025,20,Oct,13:34,2025,laTrompette.fr,Mon Aug 15 08:31:08 +0000 2016,0,492,162

In [16]:
dt.date = dt.date.str.slice(stop=3)
dt

,username,tweet,date,day,month,hour,year,name,creation,year_of_creation,followers,following
0,admzawa,@SherazadeSmh Y a Bcp de folle on le sait tqt ...,Mon,20,Oct,18:50,2025,Adam🇵🇸,Tue May 17 19:16:46 +0000 2022,0,14,129
1,zipetteenfolie,Le mec qui a inventé la depression viens discu...,Mon,20,Oct,18:49,2025,3pm.mvt,Tue Jan 01 14:37:58 +0000 2019,0,284,1053
2,Tej4s27,Post Travis concert depression,Mon,20,Oct,18:48,2025,kami,Sat Jan 20 08:02:37 +0000 2024,0,726,397
3,ssclim77,Ce qu'une dépression peut faire à ta santé aus...,Mon,20,Oct,18:47,2025,Moh 🇲🇦,Mon Dec 16 10:46:56 +0000 2024,0,838,458
4,koruxy1,@nominomm si elle était en depression ca expli...,Mon,20,Oct,18:40,2025,koruxy,Mon Sep 19 06:38:06 +0000 2022,0,40,146
...,...,...,...,...,...,...,...,...,...,...,...,...
175,Peguy_Certifie,@ActuFoot_ 😂😂😂😂😂😂😂😂😂😂😂😂😂LA DEPRESSION VA TUER ...,Mon,20,Oct,13:34,2025,💀 𝐌𝐑. 𝐓 𝐎 𝐍 𝐓 𝐈 𝐍 𝐄 🩸,Fri Oct 20 19:07:56 +0000 2017,0,42717,470
176,iwisxh,Vous voyez ça ? Ça m’écœure. Je me bâts depuis...,Mon,20,Oct,13:34,2025,❯❯❯❯,Wed Aug 28 11:40:51 +0000 2019,0,158,175
177,MonaRodriguezzz,Post vacation depression,Mon,20,Oct,13:34,2025,Ms Rodriguez,Sat Aug 24 23:25:43 +0000 2019,0,367,305
178,kindormad,@Baby_Princess_L Est ce que j’ai dit ça même? ...,Mon,20,Oct,13:34,2025,Abe 🍉,Thu May 08 20:41:43 +0000 2014,0,671,560
179,laTrompette_fr,Donner des médicaments aux personnes souffrant...,Mon,20,Oct,13:34,2025,laTrompette.fr,Mon Aug 15 08:31:08 +0000 2016,0,492,162

In [17]:
dt.dtypes

username            object
tweet               object
date                object
day                 object
month               object
hour                object
year                object
name                object
creation            object
year_of_creation     int64
followers            int64
following            int64
dtype: object

In [19]:
dt.year_of_creation = dt.creation.str.slice(-4)

In [20]:
dt["creation"] = dt.creation.str.slice(stop=10)

In [21]:
dt

,username,tweet,date,day,month,hour,year,name,creation,year_of_creation,followers,following
0,admzawa,@SherazadeSmh Y a Bcp de folle on le sait tqt ...,Mon,20,Oct,18:50,2025,Adam🇵🇸,Tue May 17,2022,14,129
1,zipetteenfolie,Le mec qui a inventé la depression viens discu...,Mon,20,Oct,18:49,2025,3pm.mvt,Tue Jan 01,2019,284,1053
2,Tej4s27,Post Travis concert depression,Mon,20,Oct,18:48,2025,kami,Sat Jan 20,2024,726,397
3,ssclim77,Ce qu'une dépression peut faire à ta santé aus...,Mon,20,Oct,18:47,2025,Moh 🇲🇦,Mon Dec 16,2024,838,458
4,koruxy1,@nominomm si elle était en depression ca expli...,Mon,20,Oct,18:40,2025,koruxy,Mon Sep 19,2022,40,146
...,...,...,...,...,...,...,...,...,...,...,...,...
175,Peguy_Certifie,@ActuFoot_ 😂😂😂😂😂😂😂😂😂😂😂😂😂LA DEPRESSION VA TUER ...,Mon,20,Oct,13:34,2025,💀 𝐌𝐑. 𝐓 𝐎 𝐍 𝐓 𝐈 𝐍 𝐄 🩸,Fri Oct 20,2017,42717,470
176,iwisxh,Vous voyez ça ? Ça m’écœure. Je me bâts depuis...,Mon,20,Oct,13:34,2025,❯❯❯❯,Wed Aug 28,2019,158,175
177,MonaRodriguezzz,Post vacation depression,Mon,20,Oct,13:34,2025,Ms Rodriguez,Sat Aug 24,2019,367,305
178,kindormad,@Baby_Princess_L Est ce que j’ai dit ça même? ...,Mon,20,Oct,13:34,2025,Abe 🍉,Thu May 08,2014,671,560
179,laTrompette_fr,Donner des médicaments aux personnes souffrant...,Mon,20,Oct,13:34,2025,laTrompette.fr,Mon Aug 15,2016,492,162

In [22]:
dt = dt.astype ({
        "day":int,
        "year":int,
        "year_of_creation":int
})