<h3>Import useful librairies and load csv file created previously</h3>

In [1]:
import pandas as pd
import numpy as np

In [2]:
dt = pd.read_csv("dirtytweets.csv")
dt

,username,tweet,date,name,creation,followers,following
0,admzawa,@SherazadeSmh Y a Bcp de folle on le sait tqt ...,Mon Oct 20 18:50:00 +0000 2025,Adam🇵🇸,Tue May 17 19:16:46 +0000 2022,14,129
1,zipetteenfolie,Le mec qui a inventé la depression viens discu...,Mon Oct 20 18:49:21 +0000 2025,3pm.mvt,Tue Jan 01 14:37:58 +0000 2019,284,1053
2,Tej4s27,Post Travis concert depression,Mon Oct 20 18:48:00 +0000 2025,kami,Sat Jan 20 08:02:37 +0000 2024,726,397
3,ssclim77,Ce qu'une dépression peut faire à ta santé aus...,Mon Oct 20 18:47:45 +0000 2025,Moh 🇲🇦,Mon Dec 16 10:46:56 +0000 2024,838,458
4,koruxy1,@nominomm si elle était en depression ca expli...,Mon Oct 20 18:40:21 +0000 2025,koruxy,Mon Sep 19 06:38:06 +0000 2022,40,146
...,...,...,...,...,...,...,...
175,Peguy_Certifie,@ActuFoot_ 😂😂😂😂😂😂😂😂😂😂😂😂😂\n\nLA DEPRESSION VA T...,Mon Oct 20 13:34:51 +0000 2025,💀 𝐌𝐑. 𝐓 𝐎 𝐍 𝐓 𝐈 𝐍 𝐄 🩸,Fri Oct 20 19:07:56 +0000 2017,42717,470
176,iwisxh,Vous voyez ça ? Ça m’écœure. Je me bâts depuis...,Mon Oct 20 13:34:48 +0000 2025,❯❯❯❯,Wed Aug 28 11:40:51 +0000 2019,158,175
177,MonaRodriguezzz,Post vacation depression,Mon Oct 20 13:34:47 +0000 2025,Ms Rodriguez,Sat Aug 24 23:25:43 +0000 2019,367,305
178,kindormad,@Baby_Princess_L Est ce que j’ai dit ça même? ...,Mon Oct 20 13:34:33 +0000 2025,Abe 🍉,Thu May 08 20:41:43 +0000 2014,671,560
179,laTrompette_fr,Donner des médicaments aux personnes souffrant...,Mon Oct 20 13:34:24 +0000 2025,laTrompette.fr,Mon Aug 15 08:31:08 +0000 2016,492,162

<h3>Let's remove the unnecessary text format</h3>

In [3]:
import emoji

In [4]:
dt["tweet"] = dt['tweet'].str.replace("\n", "")

In [5]:
dt["tweet"] = dt["tweet"].apply(lambda x : emoji.replace_emoji(x, ""))

In [6]:
dt["tweet"] = dt["tweet"].str.replace(r"http\S+|@\S+|#\S+", "", regex=True)
dt

,username,tweet,date,name,creation,followers,following
0,admzawa,Y a Bcp de folle on le sait tqt pas pas besoi...,Mon Oct 20 18:50:00 +0000 2025,Adam🇵🇸,Tue May 17 19:16:46 +0000 2022,14,129
1,zipetteenfolie,Le mec qui a inventé la depression viens discu...,Mon Oct 20 18:49:21 +0000 2025,3pm.mvt,Tue Jan 01 14:37:58 +0000 2019,284,1053
2,Tej4s27,Post Travis concert depression,Mon Oct 20 18:48:00 +0000 2025,kami,Sat Jan 20 08:02:37 +0000 2024,726,397
3,ssclim77,Ce qu'une dépression peut faire à ta santé aus...,Mon Oct 20 18:47:45 +0000 2025,Moh 🇲🇦,Mon Dec 16 10:46:56 +0000 2024,838,458
4,koruxy1,si elle était en depression ca explique les t...,Mon Oct 20 18:40:21 +0000 2025,koruxy,Mon Sep 19 06:38:06 +0000 2022,40,146
...,...,...,...,...,...,...,...
175,Peguy_Certifie,LA DEPRESSION VA TUER CE GOSSE,Mon Oct 20 13:34:51 +0000 2025,💀 𝐌𝐑. 𝐓 𝐎 𝐍 𝐓 𝐈 𝐍 𝐄 🩸,Fri Oct 20 19:07:56 +0000 2017,42717,470
176,iwisxh,Vous voyez ça ? Ça m’écœure. Je me bâts depuis...,Mon Oct 20 13:34:48 +0000 2025,❯❯❯❯,Wed Aug 28 11:40:51 +0000 2019,158,175
177,MonaRodriguezzz,Post vacation depression,Mon Oct 20 13:34:47 +0000 2025,Ms Rodriguez,Sat Aug 24 23:25:43 +0000 2019,367,305
178,kindormad,Est ce que j’ai dit ça même? J’étais certaine...,Mon Oct 20 13:34:33 +0000 2025,Abe 🍉,Thu May 08 20:41:43 +0000 2014,671,560
179,laTrompette_fr,Donner des médicaments aux personnes souffrant...,Mon Oct 20 13:34:24 +0000 2025,laTrompette.fr,Mon Aug 15 08:31:08 +0000 2016,492,162

<h3>Now le's work on the date and time column</h3>

In [7]:
dt.insert(3, "hour", 0)
dt.insert(4,"year", 0)
dt.insert(7, "year_of_creation", 0)

In [8]:
# All the dates are written the same way : 'Day Month Day(digit)' & at the end the year
# So the format is the same : 3 letters for the day + " " + 3 letters for the month + " " + 2 digits for the day
# We want to export the year for the date to the year column created previously

In [9]:
dt["hour"] = dt['date'].str[11:16]
dt

,username,tweet,date,hour,year,name,creation,year_of_creation,followers,following
0,admzawa,Y a Bcp de folle on le sait tqt pas pas besoi...,Mon Oct 20 18:50:00 +0000 2025,18:50,0,Adam🇵🇸,Tue May 17 19:16:46 +0000 2022,0,14,129
1,zipetteenfolie,Le mec qui a inventé la depression viens discu...,Mon Oct 20 18:49:21 +0000 2025,18:49,0,3pm.mvt,Tue Jan 01 14:37:58 +0000 2019,0,284,1053
2,Tej4s27,Post Travis concert depression,Mon Oct 20 18:48:00 +0000 2025,18:48,0,kami,Sat Jan 20 08:02:37 +0000 2024,0,726,397
3,ssclim77,Ce qu'une dépression peut faire à ta santé aus...,Mon Oct 20 18:47:45 +0000 2025,18:47,0,Moh 🇲🇦,Mon Dec 16 10:46:56 +0000 2024,0,838,458
4,koruxy1,si elle était en depression ca explique les t...,Mon Oct 20 18:40:21 +0000 2025,18:40,0,koruxy,Mon Sep 19 06:38:06 +0000 2022,0,40,146
...,...,...,...,...,...,...,...,...,...,...
175,Peguy_Certifie,LA DEPRESSION VA TUER CE GOSSE,Mon Oct 20 13:34:51 +0000 2025,13:34,0,💀 𝐌𝐑. 𝐓 𝐎 𝐍 𝐓 𝐈 𝐍 𝐄 🩸,Fri Oct 20 19:07:56 +0000 2017,0,42717,470
176,iwisxh,Vous voyez ça ? Ça m’écœure. Je me bâts depuis...,Mon Oct 20 13:34:48 +0000 2025,13:34,0,❯❯❯❯,Wed Aug 28 11:40:51 +0000 2019,0,158,175
177,MonaRodriguezzz,Post vacation depression,Mon Oct 20 13:34:47 +0000 2025,13:34,0,Ms Rodriguez,Sat Aug 24 23:25:43 +0000 2019,0,367,305
178,kindormad,Est ce que j’ai dit ça même? J’étais certaine...,Mon Oct 20 13:34:33 +0000 2025,13:34,0,Abe 🍉,Thu May 08 20:41:43 +0000 2014,0,671,560
179,laTrompette_fr,Donner des médicaments aux personnes souffrant...,Mon Oct 20 13:34:24 +0000 2025,13:34,0,laTrompette.fr,Mon Aug 15 08:31:08 +0000 2016,0,492,162

In [10]:
dt["year"] = dt["date"].str.slice(-4)

In [11]:
dt

,username,tweet,date,hour,year,name,creation,year_of_creation,followers,following
0,admzawa,Y a Bcp de folle on le sait tqt pas pas besoi...,Mon Oct 20 18:50:00 +0000 2025,18:50,2025,Adam🇵🇸,Tue May 17 19:16:46 +0000 2022,0,14,129
1,zipetteenfolie,Le mec qui a inventé la depression viens discu...,Mon Oct 20 18:49:21 +0000 2025,18:49,2025,3pm.mvt,Tue Jan 01 14:37:58 +0000 2019,0,284,1053
2,Tej4s27,Post Travis concert depression,Mon Oct 20 18:48:00 +0000 2025,18:48,2025,kami,Sat Jan 20 08:02:37 +0000 2024,0,726,397
3,ssclim77,Ce qu'une dépression peut faire à ta santé aus...,Mon Oct 20 18:47:45 +0000 2025,18:47,2025,Moh 🇲🇦,Mon Dec 16 10:46:56 +0000 2024,0,838,458
4,koruxy1,si elle était en depression ca explique les t...,Mon Oct 20 18:40:21 +0000 2025,18:40,2025,koruxy,Mon Sep 19 06:38:06 +0000 2022,0,40,146
...,...,...,...,...,...,...,...,...,...,...
175,Peguy_Certifie,LA DEPRESSION VA TUER CE GOSSE,Mon Oct 20 13:34:51 +0000 2025,13:34,2025,💀 𝐌𝐑. 𝐓 𝐎 𝐍 𝐓 𝐈 𝐍 𝐄 🩸,Fri Oct 20 19:07:56 +0000 2017,0,42717,470
176,iwisxh,Vous voyez ça ? Ça m’écœure. Je me bâts depuis...,Mon Oct 20 13:34:48 +0000 2025,13:34,2025,❯❯❯❯,Wed Aug 28 11:40:51 +0000 2019,0,158,175
177,MonaRodriguezzz,Post vacation depression,Mon Oct 20 13:34:47 +0000 2025,13:34,2025,Ms Rodriguez,Sat Aug 24 23:25:43 +0000 2019,0,367,305
178,kindormad,Est ce que j’ai dit ça même? J’étais certaine...,Mon Oct 20 13:34:33 +0000 2025,13:34,2025,Abe 🍉,Thu May 08 20:41:43 +0000 2014,0,671,560
179,laTrompette_fr,Donner des médicaments aux personnes souffrant...,Mon Oct 20 13:34:24 +0000 2025,13:34,2025,laTrompette.fr,Mon Aug 15 08:31:08 +0000 2016,0,492,162

In [12]:
dt.insert(3,"day", 0)

In [13]:
dt.day = dt.date.str[8:10]
dt

,username,tweet,date,day,hour,year,name,creation,year_of_creation,followers,following
0,admzawa,Y a Bcp de folle on le sait tqt pas pas besoi...,Mon Oct 20 18:50:00 +0000 2025,20,18:50,2025,Adam🇵🇸,Tue May 17 19:16:46 +0000 2022,0,14,129
1,zipetteenfolie,Le mec qui a inventé la depression viens discu...,Mon Oct 20 18:49:21 +0000 2025,20,18:49,2025,3pm.mvt,Tue Jan 01 14:37:58 +0000 2019,0,284,1053
2,Tej4s27,Post Travis concert depression,Mon Oct 20 18:48:00 +0000 2025,20,18:48,2025,kami,Sat Jan 20 08:02:37 +0000 2024,0,726,397
3,ssclim77,Ce qu'une dépression peut faire à ta santé aus...,Mon Oct 20 18:47:45 +0000 2025,20,18:47,2025,Moh 🇲🇦,Mon Dec 16 10:46:56 +0000 2024,0,838,458
4,koruxy1,si elle était en depression ca explique les t...,Mon Oct 20 18:40:21 +0000 2025,20,18:40,2025,koruxy,Mon Sep 19 06:38:06 +0000 2022,0,40,146
...,...,...,...,...,...,...,...,...,...,...,...
175,Peguy_Certifie,LA DEPRESSION VA TUER CE GOSSE,Mon Oct 20 13:34:51 +0000 2025,20,13:34,2025,💀 𝐌𝐑. 𝐓 𝐎 𝐍 𝐓 𝐈 𝐍 𝐄 🩸,Fri Oct 20 19:07:56 +0000 2017,0,42717,470
176,iwisxh,Vous voyez ça ? Ça m’écœure. Je me bâts depuis...,Mon Oct 20 13:34:48 +0000 2025,20,13:34,2025,❯❯❯❯,Wed Aug 28 11:40:51 +0000 2019,0,158,175
177,MonaRodriguezzz,Post vacation depression,Mon Oct 20 13:34:47 +0000 2025,20,13:34,2025,Ms Rodriguez,Sat Aug 24 23:25:43 +0000 2019,0,367,305
178,kindormad,Est ce que j’ai dit ça même? J’étais certaine...,Mon Oct 20 13:34:33 +0000 2025,20,13:34,2025,Abe 🍉,Thu May 08 20:41:43 +0000 2014,0,671,560
179,laTrompette_fr,Donner des médicaments aux personnes souffrant...,Mon Oct 20 13:34:24 +0000 2025,20,13:34,2025,laTrompette.fr,Mon Aug 15 08:31:08 +0000 2016,0,492,162

In [14]:
dt.insert(4,"month",0)

In [15]:
dt.month = dt.date.str[4:7]
dt

,username,tweet,date,day,month,hour,year,name,creation,year_of_creation,followers,following
0,admzawa,Y a Bcp de folle on le sait tqt pas pas besoi...,Mon Oct 20 18:50:00 +0000 2025,20,Oct,18:50,2025,Adam🇵🇸,Tue May 17 19:16:46 +0000 2022,0,14,129
1,zipetteenfolie,Le mec qui a inventé la depression viens discu...,Mon Oct 20 18:49:21 +0000 2025,20,Oct,18:49,2025,3pm.mvt,Tue Jan 01 14:37:58 +0000 2019,0,284,1053
2,Tej4s27,Post Travis concert depression,Mon Oct 20 18:48:00 +0000 2025,20,Oct,18:48,2025,kami,Sat Jan 20 08:02:37 +0000 2024,0,726,397
3,ssclim77,Ce qu'une dépression peut faire à ta santé aus...,Mon Oct 20 18:47:45 +0000 2025,20,Oct,18:47,2025,Moh 🇲🇦,Mon Dec 16 10:46:56 +0000 2024,0,838,458
4,koruxy1,si elle était en depression ca explique les t...,Mon Oct 20 18:40:21 +0000 2025,20,Oct,18:40,2025,koruxy,Mon Sep 19 06:38:06 +0000 2022,0,40,146
...,...,...,...,...,...,...,...,...,...,...,...,...
175,Peguy_Certifie,LA DEPRESSION VA TUER CE GOSSE,Mon Oct 20 13:34:51 +0000 2025,20,Oct,13:34,2025,💀 𝐌𝐑. 𝐓 𝐎 𝐍 𝐓 𝐈 𝐍 𝐄 🩸,Fri Oct 20 19:07:56 +0000 2017,0,42717,470
176,iwisxh,Vous voyez ça ? Ça m’écœure. Je me bâts depuis...,Mon Oct 20 13:34:48 +0000 2025,20,Oct,13:34,2025,❯❯❯❯,Wed Aug 28 11:40:51 +0000 2019,0,158,175
177,MonaRodriguezzz,Post vacation depression,Mon Oct 20 13:34:47 +0000 2025,20,Oct,13:34,2025,Ms Rodriguez,Sat Aug 24 23:25:43 +0000 2019,0,367,305
178,kindormad,Est ce que j’ai dit ça même? J’étais certaine...,Mon Oct 20 13:34:33 +0000 2025,20,Oct,13:34,2025,Abe 🍉,Thu May 08 20:41:43 +0000 2014,0,671,560
179,laTrompette_fr,Donner des médicaments aux personnes souffrant...,Mon Oct 20 13:34:24 +0000 2025,20,Oct,13:34,2025,laTrompette.fr,Mon Aug 15 08:31:08 +0000 2016,0,492,162

In [16]:
dt.date = dt.date.str.slice(stop=3)
dt

,username,tweet,date,day,month,hour,year,name,creation,year_of_creation,followers,following
0,admzawa,Y a Bcp de folle on le sait tqt pas pas besoi...,Mon,20,Oct,18:50,2025,Adam🇵🇸,Tue May 17 19:16:46 +0000 2022,0,14,129
1,zipetteenfolie,Le mec qui a inventé la depression viens discu...,Mon,20,Oct,18:49,2025,3pm.mvt,Tue Jan 01 14:37:58 +0000 2019,0,284,1053
2,Tej4s27,Post Travis concert depression,Mon,20,Oct,18:48,2025,kami,Sat Jan 20 08:02:37 +0000 2024,0,726,397
3,ssclim77,Ce qu'une dépression peut faire à ta santé aus...,Mon,20,Oct,18:47,2025,Moh 🇲🇦,Mon Dec 16 10:46:56 +0000 2024,0,838,458
4,koruxy1,si elle était en depression ca explique les t...,Mon,20,Oct,18:40,2025,koruxy,Mon Sep 19 06:38:06 +0000 2022,0,40,146
...,...,...,...,...,...,...,...,...,...,...,...,...
175,Peguy_Certifie,LA DEPRESSION VA TUER CE GOSSE,Mon,20,Oct,13:34,2025,💀 𝐌𝐑. 𝐓 𝐎 𝐍 𝐓 𝐈 𝐍 𝐄 🩸,Fri Oct 20 19:07:56 +0000 2017,0,42717,470
176,iwisxh,Vous voyez ça ? Ça m’écœure. Je me bâts depuis...,Mon,20,Oct,13:34,2025,❯❯❯❯,Wed Aug 28 11:40:51 +0000 2019,0,158,175
177,MonaRodriguezzz,Post vacation depression,Mon,20,Oct,13:34,2025,Ms Rodriguez,Sat Aug 24 23:25:43 +0000 2019,0,367,305
178,kindormad,Est ce que j’ai dit ça même? J’étais certaine...,Mon,20,Oct,13:34,2025,Abe 🍉,Thu May 08 20:41:43 +0000 2014,0,671,560
179,laTrompette_fr,Donner des médicaments aux personnes souffrant...,Mon,20,Oct,13:34,2025,laTrompette.fr,Mon Aug 15 08:31:08 +0000 2016,0,492,162

In [17]:
dt.dtypes

username            object
tweet               object
date                object
day                 object
month               object
hour                object
year                object
name                object
creation            object
year_of_creation     int64
followers            int64
following            int64
dtype: object

In [18]:
dt.year_of_creation = dt.creation.str.slice(-4)

In [19]:
dt["creation"] = dt.creation.str.slice(stop=10)

In [20]:
dt

,username,tweet,date,day,month,hour,year,name,creation,year_of_creation,followers,following
0,admzawa,Y a Bcp de folle on le sait tqt pas pas besoi...,Mon,20,Oct,18:50,2025,Adam🇵🇸,Tue May 17,2022,14,129
1,zipetteenfolie,Le mec qui a inventé la depression viens discu...,Mon,20,Oct,18:49,2025,3pm.mvt,Tue Jan 01,2019,284,1053
2,Tej4s27,Post Travis concert depression,Mon,20,Oct,18:48,2025,kami,Sat Jan 20,2024,726,397
3,ssclim77,Ce qu'une dépression peut faire à ta santé aus...,Mon,20,Oct,18:47,2025,Moh 🇲🇦,Mon Dec 16,2024,838,458
4,koruxy1,si elle était en depression ca explique les t...,Mon,20,Oct,18:40,2025,koruxy,Mon Sep 19,2022,40,146
...,...,...,...,...,...,...,...,...,...,...,...,...
175,Peguy_Certifie,LA DEPRESSION VA TUER CE GOSSE,Mon,20,Oct,13:34,2025,💀 𝐌𝐑. 𝐓 𝐎 𝐍 𝐓 𝐈 𝐍 𝐄 🩸,Fri Oct 20,2017,42717,470
176,iwisxh,Vous voyez ça ? Ça m’écœure. Je me bâts depuis...,Mon,20,Oct,13:34,2025,❯❯❯❯,Wed Aug 28,2019,158,175
177,MonaRodriguezzz,Post vacation depression,Mon,20,Oct,13:34,2025,Ms Rodriguez,Sat Aug 24,2019,367,305
178,kindormad,Est ce que j’ai dit ça même? J’étais certaine...,Mon,20,Oct,13:34,2025,Abe 🍉,Thu May 08,2014,671,560
179,laTrompette_fr,Donner des médicaments aux personnes souffrant...,Mon,20,Oct,13:34,2025,laTrompette.fr,Mon Aug 15,2016,492,162

In [21]:
dt = dt.astype ({
        "day":int,
        "year":int,
        "year_of_creation":int
})

In [22]:
dt

,username,tweet,date,day,month,hour,year,name,creation,year_of_creation,followers,following
0,admzawa,Y a Bcp de folle on le sait tqt pas pas besoi...,Mon,20,Oct,18:50,2025,Adam🇵🇸,Tue May 17,2022,14,129
1,zipetteenfolie,Le mec qui a inventé la depression viens discu...,Mon,20,Oct,18:49,2025,3pm.mvt,Tue Jan 01,2019,284,1053
2,Tej4s27,Post Travis concert depression,Mon,20,Oct,18:48,2025,kami,Sat Jan 20,2024,726,397
3,ssclim77,Ce qu'une dépression peut faire à ta santé aus...,Mon,20,Oct,18:47,2025,Moh 🇲🇦,Mon Dec 16,2024,838,458
4,koruxy1,si elle était en depression ca explique les t...,Mon,20,Oct,18:40,2025,koruxy,Mon Sep 19,2022,40,146
...,...,...,...,...,...,...,...,...,...,...,...,...
175,Peguy_Certifie,LA DEPRESSION VA TUER CE GOSSE,Mon,20,Oct,13:34,2025,💀 𝐌𝐑. 𝐓 𝐎 𝐍 𝐓 𝐈 𝐍 𝐄 🩸,Fri Oct 20,2017,42717,470
176,iwisxh,Vous voyez ça ? Ça m’écœure. Je me bâts depuis...,Mon,20,Oct,13:34,2025,❯❯❯❯,Wed Aug 28,2019,158,175
177,MonaRodriguezzz,Post vacation depression,Mon,20,Oct,13:34,2025,Ms Rodriguez,Sat Aug 24,2019,367,305
178,kindormad,Est ce que j’ai dit ça même? J’étais certaine...,Mon,20,Oct,13:34,2025,Abe 🍉,Thu May 08,2014,671,560
179,laTrompette_fr,Donner des médicaments aux personnes souffrant...,Mon,20,Oct,13:34,2025,laTrompette.fr,Mon Aug 15,2016,492,162

In [28]:
dt.to_json("cleanedTweets.json", orient="records")