<h3>Import useful librairies and load csv file created previously</h3>

In [2]:
import pandas as pd
import numpy as np

In [4]:
dt = pd.read_json("ressource/fetchedTweets.json")
dt

,username,tweet,url,date,depression,createdAt,followers,following,photo
0,admzawa,@SherazadeSmh Y a Bcp de folle on le sait tqt ...,https://x.com/admzawa/status/1980345773310242891,2025-10-20 18:50:00+00:00,NaN,Tue May 17 19:16:46 +0000 2022,14,129,https://pbs.twimg.com/profile_images/185854882...
1,zipetteenfolie,Le mec qui a inventé la depression viens discu...,https://x.com/zipetteenfolie/status/1980345612...,2025-10-20 18:49:21+00:00,NaN,Tue Jan 01 14:37:58 +0000 2019,284,1053,https://pbs.twimg.com/profile_images/187124118...
2,Tej4s27,Post Travis concert depression,https://x.com/Tej4s27/status/1980345272514601086,2025-10-20 18:48:00+00:00,NaN,Sat Jan 20 08:02:37 +0000 2024,726,397,https://pbs.twimg.com/profile_images/197816346...
3,ssclim77,Ce qu'une dépression peut faire à ta santé aus...,https://x.com/ssclim77/status/1980345207045689795,2025-10-20 18:47:45+00:00,NaN,Mon Dec 16 10:46:56 +0000 2024,838,458,https://pbs.twimg.com/profile_images/198032758...
4,koruxy1,@nominomm si elle était en depression ca expli...,https://x.com/koruxy1/status/1980343346104267066,2025-10-20 18:40:21+00:00,NaN,Mon Sep 19 06:38:06 +0000 2022,40,146,https://pbs.twimg.com/profile_images/173296330...
...,...,...,...,...,...,...,...,...,...
175,Peguy_Certifie,@ActuFoot_ 😂😂😂😂😂😂😂😂😂😂😂😂😂\n\nLA DEPRESSION VA T...,https://x.com/Peguy_Certifie/status/1980266464...,2025-10-20 13:34:51+00:00,NaN,Fri Oct 20 19:07:56 +0000 2017,42717,470,https://pbs.twimg.com/profile_images/186977496...
176,iwisxh,Vous voyez ça ? Ça m’écœure. Je me bâts depuis...,https://x.com/iwisxh/status/1980266453837258967,2025-10-20 13:34:48+00:00,NaN,Wed Aug 28 11:40:51 +0000 2019,158,175,https://pbs.twimg.com/profile_images/197118170...
177,MonaRodriguezzz,Post vacation depression,https://x.com/MonaRodriguezzz/status/198026644...,2025-10-20 13:34:47+00:00,NaN,Sat Aug 24 23:25:43 +0000 2019,367,305,https://pbs.twimg.com/profile_images/191318622...
178,kindormad,@Baby_Princess_L Est ce que j’ai dit ça même? ...,https://x.com/kindormad/status/198026638820057...,2025-10-20 13:34:33+00:00,NaN,Thu May 08 20:41:43 +0000 2014,671,560,https://pbs.twimg.com/profile_images/196723707...
179,laTrompette_fr,Donner des médicaments aux personnes souffrant...,https://x.com/laTrompette_fr/status/1980266350...,2025-10-20 13:34:24+00:00,NaN,Mon Aug 15 08:31:08 +0000 2016,492,162,https://pbs.twimg.com/profile_images/765104340...

<h3>Let's remove the unnecessary text format</h3>

In [5]:
import emoji

In [6]:
dt["tweet"] = dt['tweet'].str.replace("\n", "")

In [7]:
dt["tweet"] = dt["tweet"].apply(lambda x : emoji.replace_emoji(x, ""))

In [8]:
dt["tweet"] = dt["tweet"].str.replace(r"http\S+|@\S+|#\S+", "", regex=True)
dt

,username,tweet,url,date,depression,createdAt,followers,following,photo
0,admzawa,Y a Bcp de folle on le sait tqt pas pas besoi...,https://x.com/admzawa/status/1980345773310242891,2025-10-20 18:50:00+00:00,NaN,Tue May 17 19:16:46 +0000 2022,14,129,https://pbs.twimg.com/profile_images/185854882...
1,zipetteenfolie,Le mec qui a inventé la depression viens discu...,https://x.com/zipetteenfolie/status/1980345612...,2025-10-20 18:49:21+00:00,NaN,Tue Jan 01 14:37:58 +0000 2019,284,1053,https://pbs.twimg.com/profile_images/187124118...
2,Tej4s27,Post Travis concert depression,https://x.com/Tej4s27/status/1980345272514601086,2025-10-20 18:48:00+00:00,NaN,Sat Jan 20 08:02:37 +0000 2024,726,397,https://pbs.twimg.com/profile_images/197816346...
3,ssclim77,Ce qu'une dépression peut faire à ta santé aus...,https://x.com/ssclim77/status/1980345207045689795,2025-10-20 18:47:45+00:00,NaN,Mon Dec 16 10:46:56 +0000 2024,838,458,https://pbs.twimg.com/profile_images/198032758...
4,koruxy1,si elle était en depression ca explique les t...,https://x.com/koruxy1/status/1980343346104267066,2025-10-20 18:40:21+00:00,NaN,Mon Sep 19 06:38:06 +0000 2022,40,146,https://pbs.twimg.com/profile_images/173296330...
...,...,...,...,...,...,...,...,...,...
175,Peguy_Certifie,LA DEPRESSION VA TUER CE GOSSE,https://x.com/Peguy_Certifie/status/1980266464...,2025-10-20 13:34:51+00:00,NaN,Fri Oct 20 19:07:56 +0000 2017,42717,470,https://pbs.twimg.com/profile_images/186977496...
176,iwisxh,Vous voyez ça ? Ça m’écœure. Je me bâts depuis...,https://x.com/iwisxh/status/1980266453837258967,2025-10-20 13:34:48+00:00,NaN,Wed Aug 28 11:40:51 +0000 2019,158,175,https://pbs.twimg.com/profile_images/197118170...
177,MonaRodriguezzz,Post vacation depression,https://x.com/MonaRodriguezzz/status/198026644...,2025-10-20 13:34:47+00:00,NaN,Sat Aug 24 23:25:43 +0000 2019,367,305,https://pbs.twimg.com/profile_images/191318622...
178,kindormad,Est ce que j’ai dit ça même? J’étais certaine...,https://x.com/kindormad/status/198026638820057...,2025-10-20 13:34:33+00:00,NaN,Thu May 08 20:41:43 +0000 2014,671,560,https://pbs.twimg.com/profile_images/196723707...
179,laTrompette_fr,Donner des médicaments aux personnes souffrant...,https://x.com/laTrompette_fr/status/1980266350...,2025-10-20 13:34:24+00:00,NaN,Mon Aug 15 08:31:08 +0000 2016,492,162,https://pbs.twimg.com/profile_images/765104340...

<h3>Now le's work on the date and time column</h3>

In [9]:
dt.insert(3,"day", 0)
dt.insert(4, "month", 0)
dt.insert(5,"year", 0)
dt.insert(6,"hour",0)
dt.insert(9, "creation",0)

In [10]:
# All the dates are written the same way : 'Day Month Day(digit)' & at the end the year
# So the format is the same : 3 letters for the day + " " + 3 letters for the month + " " + 2 digits for the day
# We want to export the year for the date to the year column created previously

In [11]:
dt['date'] = dt['date'].dt.strftime('%Y-%m-%d %H:%M:%S %Z')  #convert a datetime into a str

In [12]:
dt.date = dt.date.str.replace(" UTC", "")

In [13]:
dt["hour"] = dt['date'].str[11:16]
dt["year"] = dt["date"].str[0:4]
dt['day'] = dt['date'].str[8:10]
dt.month = dt.date.str[5:7]

dt

,username,tweet,url,day,month,year,hour,date,depression,creation,createdAt,followers,following,photo
0,admzawa,Y a Bcp de folle on le sait tqt pas pas besoi...,https://x.com/admzawa/status/1980345773310242891,20,10,2025,18:50,2025-10-20 18:50:00,NaN,0,Tue May 17 19:16:46 +0000 2022,14,129,https://pbs.twimg.com/profile_images/185854882...
1,zipetteenfolie,Le mec qui a inventé la depression viens discu...,https://x.com/zipetteenfolie/status/1980345612...,20,10,2025,18:49,2025-10-20 18:49:21,NaN,0,Tue Jan 01 14:37:58 +0000 2019,284,1053,https://pbs.twimg.com/profile_images/187124118...
2,Tej4s27,Post Travis concert depression,https://x.com/Tej4s27/status/1980345272514601086,20,10,2025,18:48,2025-10-20 18:48:00,NaN,0,Sat Jan 20 08:02:37 +0000 2024,726,397,https://pbs.twimg.com/profile_images/197816346...
3,ssclim77,Ce qu'une dépression peut faire à ta santé aus...,https://x.com/ssclim77/status/1980345207045689795,20,10,2025,18:47,2025-10-20 18:47:45,NaN,0,Mon Dec 16 10:46:56 +0000 2024,838,458,https://pbs.twimg.com/profile_images/198032758...
4,koruxy1,si elle était en depression ca explique les t...,https://x.com/koruxy1/status/1980343346104267066,20,10,2025,18:40,2025-10-20 18:40:21,NaN,0,Mon Sep 19 06:38:06 +0000 2022,40,146,https://pbs.twimg.com/profile_images/173296330...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,Peguy_Certifie,LA DEPRESSION VA TUER CE GOSSE,https://x.com/Peguy_Certifie/status/1980266464...,20,10,2025,13:34,2025-10-20 13:34:51,NaN,0,Fri Oct 20 19:07:56 +0000 2017,42717,470,https://pbs.twimg.com/profile_images/186977496...
176,iwisxh,Vous voyez ça ? Ça m’écœure. Je me bâts depuis...,https://x.com/iwisxh/status/1980266453837258967,20,10,2025,13:34,2025-10-20 13:34:48,NaN,0,Wed Aug 28 11:40:51 +0000 2019,158,175,https://pbs.twimg.com/profile_images/197118170...
177,MonaRodriguezzz,Post vacation depression,https://x.com/MonaRodriguezzz/status/198026644...,20,10,2025,13:34,2025-10-20 13:34:47,NaN,0,Sat Aug 24 23:25:43 +0000 2019,367,305,https://pbs.twimg.com/profile_images/191318622...
178,kindormad,Est ce que j’ai dit ça même? J’étais certaine...,https://x.com/kindormad/status/198026638820057...,20,10,2025,13:34,2025-10-20 13:34:33,NaN,0,Thu May 08 20:41:43 +0000 2014,671,560,https://pbs.twimg.com/profile_images/196723707...
179,laTrompette_fr,Donner des médicaments aux personnes souffrant...,https://x.com/laTrompette_fr/status/1980266350...,20,10,2025,13:34,2025-10-20 13:34:24,NaN,0,Mon Aug 15 08:31:08 +0000 2016,492,162,https://pbs.twimg.com/profile_images/765104340...

In [14]:
dt.drop("date", axis="columns", inplace=True)

In [15]:
dt.dtypes

username       object
tweet          object
url            object
day            object
month          object
year           object
hour           object
depression    float64
creation        int64
createdAt      object
followers       int64
following       int64
photo          object
dtype: object

In [16]:
dt.creation = dt.createdAt.str.slice(start=4, stop=10) + " " + dt.createdAt.str.slice(-4)

In [17]:
dt.drop("createdAt", axis="columns", inplace=True)
dt

,username,tweet,url,day,month,year,hour,depression,creation,followers,following,photo
0,admzawa,Y a Bcp de folle on le sait tqt pas pas besoi...,https://x.com/admzawa/status/1980345773310242891,20,10,2025,18:50,NaN,May 17 2022,14,129,https://pbs.twimg.com/profile_images/185854882...
1,zipetteenfolie,Le mec qui a inventé la depression viens discu...,https://x.com/zipetteenfolie/status/1980345612...,20,10,2025,18:49,NaN,Jan 01 2019,284,1053,https://pbs.twimg.com/profile_images/187124118...
2,Tej4s27,Post Travis concert depression,https://x.com/Tej4s27/status/1980345272514601086,20,10,2025,18:48,NaN,Jan 20 2024,726,397,https://pbs.twimg.com/profile_images/197816346...
3,ssclim77,Ce qu'une dépression peut faire à ta santé aus...,https://x.com/ssclim77/status/1980345207045689795,20,10,2025,18:47,NaN,Dec 16 2024,838,458,https://pbs.twimg.com/profile_images/198032758...
4,koruxy1,si elle était en depression ca explique les t...,https://x.com/koruxy1/status/1980343346104267066,20,10,2025,18:40,NaN,Sep 19 2022,40,146,https://pbs.twimg.com/profile_images/173296330...
...,...,...,...,...,...,...,...,...,...,...,...,...
175,Peguy_Certifie,LA DEPRESSION VA TUER CE GOSSE,https://x.com/Peguy_Certifie/status/1980266464...,20,10,2025,13:34,NaN,Oct 20 2017,42717,470,https://pbs.twimg.com/profile_images/186977496...
176,iwisxh,Vous voyez ça ? Ça m’écœure. Je me bâts depuis...,https://x.com/iwisxh/status/1980266453837258967,20,10,2025,13:34,NaN,Aug 28 2019,158,175,https://pbs.twimg.com/profile_images/197118170...
177,MonaRodriguezzz,Post vacation depression,https://x.com/MonaRodriguezzz/status/198026644...,20,10,2025,13:34,NaN,Aug 24 2019,367,305,https://pbs.twimg.com/profile_images/191318622...
178,kindormad,Est ce que j’ai dit ça même? J’étais certaine...,https://x.com/kindormad/status/198026638820057...,20,10,2025,13:34,NaN,May 08 2014,671,560,https://pbs.twimg.com/profile_images/196723707...
179,laTrompette_fr,Donner des médicaments aux personnes souffrant...,https://x.com/laTrompette_fr/status/1980266350...,20,10,2025,13:34,NaN,Aug 15 2016,492,162,https://pbs.twimg.com/profile_images/765104340...

In [18]:
dt = dt.astype ({
        "day":int,
        "year":int,
        "month":int
})

In [19]:
dt.to_json("ressource/cleanedTweets.json", orient="records")