In [ ]:
<h3>Import useful librairies and load csv file created previously</h3>

In [1]:
import pandas as pd
import numpy as np

In [2]:
dt = pd.read_json("fetchedTweets.json")
dt

,username,tweet,date,name,createdAt,followers,following
0,admzawa,@SherazadeSmh Y a Bcp de folle on le sait tqt ...,2025-10-20 18:50:00+00:00,Adam🇵🇸,Tue May 17 19:16:46 +0000 2022,14,129
1,zipetteenfolie,Le mec qui a inventé la depression viens discu...,2025-10-20 18:49:21+00:00,3pm.mvt,Tue Jan 01 14:37:58 +0000 2019,284,1053
2,Tej4s27,Post Travis concert depression,2025-10-20 18:48:00+00:00,kami,Sat Jan 20 08:02:37 +0000 2024,726,397
3,ssclim77,Ce qu'une dépression peut faire à ta santé aus...,2025-10-20 18:47:45+00:00,Moh 🇲🇦,Mon Dec 16 10:46:56 +0000 2024,838,458
4,koruxy1,@nominomm si elle était en depression ca expli...,2025-10-20 18:40:21+00:00,koruxy,Mon Sep 19 06:38:06 +0000 2022,40,146
...,...,...,...,...,...,...,...
175,Peguy_Certifie,@ActuFoot_ 😂😂😂😂😂😂😂😂😂😂😂😂😂\n\nLA DEPRESSION VA T...,2025-10-20 13:34:51+00:00,💀 𝐌𝐑. 𝐓 𝐎 𝐍 𝐓 𝐈 𝐍 𝐄 🩸,Fri Oct 20 19:07:56 +0000 2017,42717,470
176,iwisxh,Vous voyez ça ? Ça m’écœure. Je me bâts depuis...,2025-10-20 13:34:48+00:00,❯❯❯❯,Wed Aug 28 11:40:51 +0000 2019,158,175
177,MonaRodriguezzz,Post vacation depression,2025-10-20 13:34:47+00:00,Ms Rodriguez,Sat Aug 24 23:25:43 +0000 2019,367,305
178,kindormad,@Baby_Princess_L Est ce que j’ai dit ça même? ...,2025-10-20 13:34:33+00:00,Abe 🍉,Thu May 08 20:41:43 +0000 2014,671,560
179,laTrompette_fr,Donner des médicaments aux personnes souffrant...,2025-10-20 13:34:24+00:00,laTrompette.fr,Mon Aug 15 08:31:08 +0000 2016,492,162

<h3>Let's remove the unnecessary text format</h3>

In [3]:
import emoji

In [4]:
dt["tweet"] = dt['tweet'].str.replace("\n", "")

In [5]:
dt["tweet"] = dt["tweet"].apply(lambda x : emoji.replace_emoji(x, ""))

In [6]:
dt["tweet"] = dt["tweet"].str.replace(r"http\S+|@\S+|#\S+", "", regex=True)
dt

,username,tweet,date,name,createdAt,followers,following
0,admzawa,Y a Bcp de folle on le sait tqt pas pas besoi...,2025-10-20 18:50:00+00:00,Adam🇵🇸,Tue May 17 19:16:46 +0000 2022,14,129
1,zipetteenfolie,Le mec qui a inventé la depression viens discu...,2025-10-20 18:49:21+00:00,3pm.mvt,Tue Jan 01 14:37:58 +0000 2019,284,1053
2,Tej4s27,Post Travis concert depression,2025-10-20 18:48:00+00:00,kami,Sat Jan 20 08:02:37 +0000 2024,726,397
3,ssclim77,Ce qu'une dépression peut faire à ta santé aus...,2025-10-20 18:47:45+00:00,Moh 🇲🇦,Mon Dec 16 10:46:56 +0000 2024,838,458
4,koruxy1,si elle était en depression ca explique les t...,2025-10-20 18:40:21+00:00,koruxy,Mon Sep 19 06:38:06 +0000 2022,40,146
...,...,...,...,...,...,...,...
175,Peguy_Certifie,LA DEPRESSION VA TUER CE GOSSE,2025-10-20 13:34:51+00:00,💀 𝐌𝐑. 𝐓 𝐎 𝐍 𝐓 𝐈 𝐍 𝐄 🩸,Fri Oct 20 19:07:56 +0000 2017,42717,470
176,iwisxh,Vous voyez ça ? Ça m’écœure. Je me bâts depuis...,2025-10-20 13:34:48+00:00,❯❯❯❯,Wed Aug 28 11:40:51 +0000 2019,158,175
177,MonaRodriguezzz,Post vacation depression,2025-10-20 13:34:47+00:00,Ms Rodriguez,Sat Aug 24 23:25:43 +0000 2019,367,305
178,kindormad,Est ce que j’ai dit ça même? J’étais certaine...,2025-10-20 13:34:33+00:00,Abe 🍉,Thu May 08 20:41:43 +0000 2014,671,560
179,laTrompette_fr,Donner des médicaments aux personnes souffrant...,2025-10-20 13:34:24+00:00,laTrompette.fr,Mon Aug 15 08:31:08 +0000 2016,492,162

<h3>Now le's work on the date and time column</h3>

In [7]:
dt.insert(2,"day", 0)
dt.insert(3, "month", 0)
dt.insert(4,"year", 0)
dt.insert(5,"hour",0)
dt.insert(8, "creation",0)

In [8]:
# All the dates are written the same way : 'Day Month Day(digit)' & at the end the year
# So the format is the same : 3 letters for the day + " " + 3 letters for the month + " " + 2 digits for the day
# We want to export the year for the date to the year column created previously

In [9]:
dt['date'] = dt['date'].dt.strftime('%Y-%m-%d %H:%M:%S %Z')  #convert a datetime into a str

In [10]:
dt.date = dt.date.str.replace(" UTC", "")

In [11]:
dt["hour"] = dt['date'].str[11:16]
dt["year"] = dt["date"].str[0:4]
dt['day'] = dt['date'].str[8:10]
dt.month = dt.date.str[5:7]

dt

,username,tweet,day,month,year,hour,date,name,creation,createdAt,followers,following
0,admzawa,Y a Bcp de folle on le sait tqt pas pas besoi...,20,10,2025,18:50,2025-10-20 18:50:00,Adam🇵🇸,0,Tue May 17 19:16:46 +0000 2022,14,129
1,zipetteenfolie,Le mec qui a inventé la depression viens discu...,20,10,2025,18:49,2025-10-20 18:49:21,3pm.mvt,0,Tue Jan 01 14:37:58 +0000 2019,284,1053
2,Tej4s27,Post Travis concert depression,20,10,2025,18:48,2025-10-20 18:48:00,kami,0,Sat Jan 20 08:02:37 +0000 2024,726,397
3,ssclim77,Ce qu'une dépression peut faire à ta santé aus...,20,10,2025,18:47,2025-10-20 18:47:45,Moh 🇲🇦,0,Mon Dec 16 10:46:56 +0000 2024,838,458
4,koruxy1,si elle était en depression ca explique les t...,20,10,2025,18:40,2025-10-20 18:40:21,koruxy,0,Mon Sep 19 06:38:06 +0000 2022,40,146
...,...,...,...,...,...,...,...,...,...,...,...,...
175,Peguy_Certifie,LA DEPRESSION VA TUER CE GOSSE,20,10,2025,13:34,2025-10-20 13:34:51,💀 𝐌𝐑. 𝐓 𝐎 𝐍 𝐓 𝐈 𝐍 𝐄 🩸,0,Fri Oct 20 19:07:56 +0000 2017,42717,470
176,iwisxh,Vous voyez ça ? Ça m’écœure. Je me bâts depuis...,20,10,2025,13:34,2025-10-20 13:34:48,❯❯❯❯,0,Wed Aug 28 11:40:51 +0000 2019,158,175
177,MonaRodriguezzz,Post vacation depression,20,10,2025,13:34,2025-10-20 13:34:47,Ms Rodriguez,0,Sat Aug 24 23:25:43 +0000 2019,367,305
178,kindormad,Est ce que j’ai dit ça même? J’étais certaine...,20,10,2025,13:34,2025-10-20 13:34:33,Abe 🍉,0,Thu May 08 20:41:43 +0000 2014,671,560
179,laTrompette_fr,Donner des médicaments aux personnes souffrant...,20,10,2025,13:34,2025-10-20 13:34:24,laTrompette.fr,0,Mon Aug 15 08:31:08 +0000 2016,492,162

In [12]:
dt.drop("date", axis="columns", inplace=True)

In [13]:
dt.dtypes

username     object
tweet        object
day          object
month        object
year         object
hour         object
name         object
creation      int64
createdAt    object
followers     int64
following     int64
dtype: object

In [14]:
dt.creation = dt.createdAt.str.slice(start=4, stop=10) + " " + dt.createdAt.str.slice(-4)

In [15]:
dt.drop("createdAt", axis="columns", inplace=True)
dt

,username,tweet,day,month,year,hour,name,creation,followers,following
0,admzawa,Y a Bcp de folle on le sait tqt pas pas besoi...,20,10,2025,18:50,Adam🇵🇸,May 17 2022,14,129
1,zipetteenfolie,Le mec qui a inventé la depression viens discu...,20,10,2025,18:49,3pm.mvt,Jan 01 2019,284,1053
2,Tej4s27,Post Travis concert depression,20,10,2025,18:48,kami,Jan 20 2024,726,397
3,ssclim77,Ce qu'une dépression peut faire à ta santé aus...,20,10,2025,18:47,Moh 🇲🇦,Dec 16 2024,838,458
4,koruxy1,si elle était en depression ca explique les t...,20,10,2025,18:40,koruxy,Sep 19 2022,40,146
...,...,...,...,...,...,...,...,...,...,...
175,Peguy_Certifie,LA DEPRESSION VA TUER CE GOSSE,20,10,2025,13:34,💀 𝐌𝐑. 𝐓 𝐎 𝐍 𝐓 𝐈 𝐍 𝐄 🩸,Oct 20 2017,42717,470
176,iwisxh,Vous voyez ça ? Ça m’écœure. Je me bâts depuis...,20,10,2025,13:34,❯❯❯❯,Aug 28 2019,158,175
177,MonaRodriguezzz,Post vacation depression,20,10,2025,13:34,Ms Rodriguez,Aug 24 2019,367,305
178,kindormad,Est ce que j’ai dit ça même? J’étais certaine...,20,10,2025,13:34,Abe 🍉,May 08 2014,671,560
179,laTrompette_fr,Donner des médicaments aux personnes souffrant...,20,10,2025,13:34,laTrompette.fr,Aug 15 2016,492,162

In [16]:
dt = dt.astype ({
        "day":int,
        "year":int,
        "month":int
})

In [ ]:
dt.to_json("../ressource/cleanedTweets.json", orient="records")